[package]
name = "schnose-gsi-client"
version = "2.0.0"
authors = ["AlphaKeks <alphakeks@dawn.sh>"]
edition = "2021"
description = "Desktop App for CS:GO KZ streamers"
documentation = "https://github.com/Schnose/GSIClient/wiki"
readme = "./README.md"
homepage = "https://github.com/Schnose"
repository = "https://github.com/Schnose/GSIClient"
license-file = "./LICENSE"
publish = false

[profile.release]
opt-level = "s"

[dependencies]
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

tokio = { version = "1.28.2", features = ["tracing", "rt-multi-thread"] }

serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"

gokz_rs = "0.19.2"
schnose_gsi = { version = "0.4.0", features = ["gokz"] }

