[package]
name = "schnose-gsi-client"
version = "2.0.0"
authors = ["AlphaKeks <alphakeks@dawn.sh>"]
edition = "2021"
description = "Desktop App for CS:GO KZ streamers"
documentation = "https://github.com/Schnose/GSIClient/wiki"
readme = "./README.md"
homepage = "https://github.com/Schnose"
repository = "https://github.com/Schnose/GSIClient"
license-file = "./LICENSE"
publish = false

